/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e029b655-95af-42d3-8b6a-18b3502441ce",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wpcaNyo3a",
    "aws_user_pools_web_client_id": "4s0k4rrrggv6utvjbq8fsbb2jj",
    "oauth": {
        "domain": "codecontestf6f8446e-f6f8446e-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/code_contest/",
        "redirectSignOut": "http://localhost:3000/code_contest/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
