name: Project deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set environment variable
        with: # Set the secret as an input
          super_secret: ${{ secrets.REACT_APP_APIKEY }}
        env: # Or as an environment variable
          super_secret: ${{ secrets.REACT_APP_APIKEY }}
      
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: 'minecodebot'
          user_email: 'minecode.geral@gmail.com'
          personal_token: ${{ secrets.REACT_APP_APIKEY }}
          external_repository: minecode/code_contest
          publish_branch: master
          publish_dir: ./build